# Generated by Django 4.0.4 on 2022-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('keywords', models.ManyToManyField(to='keywords.datatable')),
                ('programs', models.ManyToManyField(to='keywords.program')),
            ],
        ),
    ]
