# Generated by Django 4.0.4 on 2022-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_alter_datatable_project_name'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(related_name='projects', to='keywords.datatable'),
        ),
    ]
