# Generated by Django 4.0.4 on 2022-05-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
