# Generated by Django 4.0.4 on 2022-05-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_alter_datatable_code_alter_datatable_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='project_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='keyword_type',
            field=models.IntegerField(choices=[(0, 'Code Getlink'), (1, 'Code Unzip')], default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='pass_to_decompress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
