# Generated by Django 4.0.4 on 2022-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_datatable_project_name_program_keyword_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='project_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
