# Generated by Django 4.0.4 on 2022-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_alter_datatable_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddressUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('access', models.BooleanField()),
            ],
        ),
    ]
