# Generated by Django 4.0.4 on 2022-07-27 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_ipaddressuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressuser',
            name='entered_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipaddressuser',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
