# Generated by Django 4.0.4 on 2022-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0006_ipaddressuser_entered_password_ipaddressuser_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
    ]
