# Generated by Django 4.0.4 on 2022-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taitl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='prioritize_quantity_temp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='prioritize_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
