# Generated by Django 4.0.4 on 2022-05-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taitl', '0002_datatable_prioritize_quantity_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='prioritize',
            field=models.IntegerField(default=1),
        ),
    ]
